set auto-load safe-path /
set print pretty on
set print static-members off
set print null-stop on
set print sevenbit-strings on
#set print address on
#set print frame-arguments all
#set print frame-arguments none
#set print frame-arguments scalars
