#include "canvas/Persistency/Common/Wrapper.h"
#include "critic/test/art/product-aggregation/physics-workflow/CalibConstants.h"
#include "critic/test/art/product-aggregation/physics-workflow/Fraction.h"
#include "critic/test/art/product-aggregation/physics-workflow/Geometry.h"
#include "critic/test/art/product-aggregation/physics-workflow/TrackEfficiency.h"
