#!/bin/bash

thisdir=$(cd "${BASH_SOURCE%/*}" && pwd -P)

die() {
  printf "FATAL ERROR: ${*}\n" 1>&2; exit 1
}

python3_version=$(root-config --python3-version)
python2_version=$(root-config --python2-version)
[[ "${python3_version:-${python2_version}}" =~ \
  ([[:digit:]]+(\.[[:digit:]]+)?) ]] || \
  die "unable to ascertain Python executable used by ROOT"

python=python${BASH_REMATCH[1]}
set -x
exec ${python} "${thisdir}/r10870_t.py"
